DROP DATABASE IF EXISTS DBPROJETODESKTOP;

CREATE DATABASE DBPROJETODESKTOP;

USE DBPROJETODESKTOP;

CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (100),
	ENDERECO VARCHAR (500),
	BAIRRO VARCHAR (100),
	CEP CHAR (8),
	MUNICIPIO VARCHAR (100),
	ESTADO VARCHAR (100),
	TELEFONE CHAR (10) unique,
	CELULAR CHAR (11) unique,
	EMAIL VARCHAR (100) unique,
	CPF CHAR (11) unique,
	DATANASCIMENTO DATE
);

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (100),
	ENDERECO VARCHAR (500),
	BAIRRO VARCHAR (100),
	CEP CHAR (8),
	MUNICIPIO VARCHAR (100),
	ESTADO VARCHAR (100),
	TELEFONE CHAR (10) unique,
	CELULAR CHAR (11) unique,
	EMAIL VARCHAR (100) unique,
	CPF CHAR (11) unique,
	DATANASCIMENTO DATE,
	RG CHAR (9) unique,
	CARGO VARCHAR (100),
	FUNCAO VARCHAR (100),
	DATAADMISSAO DATE,
	ESCOLARIDADE VARCHAR (100) 
);

CREATE TABLE PROCEDIMENTO(
	IDPROCEDIMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (100),
	SALA VARCHAR (100)
);

CREATE TABLE AGENDAMENTO(
	IDAGENDAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDPROCEDIMENTO INT,
	IDCLIENTE INT,
	IDFUNCIONARIO INT,
	DATA DATETIME,
	FOREIGN KEY (IDPROCEDIMENTO) REFERENCES PROCEDIMENTO (IDPROCEDIMENTO),
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE),
	FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO (IDFUNCIONARIO)
);

