DROP DATABASE IF EXISTS DBPROJETODESKTOP;

CREATE DATABASE DBPROJETODESKTOP;

USE DBPROJETODESKTOP;

CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (100),
	ENDERECO VARCHAR (500),
	BAIRRO VARCHAR (100),
	CEP CHAR (8),
	MUNICIPIO VARCHAR (100),
	ESTADO VARCHAR (100),
	TELEFONE CHAR (10) unique,
	CELULAR CHAR (13) unique,
	EMAIL VARCHAR (100) unique,
	CPF CHAR (11) unique,
	DATANASCIMENTO DATE
);

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (100),
	ENDERECO VARCHAR (500),
	BAIRRO VARCHAR (100),
	CEP CHAR (8),
	MUNICIPIO VARCHAR (100),
	ESTADO VARCHAR (100),
	TELEFONE CHAR (10) unique,
	CELULAR CHAR (13) unique,
	EMAIL VARCHAR (100) unique,
	CPF CHAR (11) unique,
	DATANASCIMENTO DATE,
	RG CHAR (9) unique,
	CARGO VARCHAR (100),
	FUNCAO VARCHAR (100),
	DATAADMISSAO DATE,
	ESCOLARIDADE VARCHAR (100) 
);

CREATE TABLE PROCEDIMENTO(
	IDPROCEDIMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (100),
	SALA VARCHAR (100)
);

CREATE TABLE AGENDAMENTO(
	IDAGENDAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDPROCEDIMENTO INT,
	IDCLIENTE INT,
	IDFUNCIONARIO INT,
	DATA DATETIME,
	STATUSAGENDAMENTO VARCHAR(45),
	FOREIGN KEY (IDPROCEDIMENTO) REFERENCES PROCEDIMENTO (IDPROCEDIMENTO),
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE),
	FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO (IDFUNCIONARIO)
);
 
insert into CLIENTE (NOME, ENDERECO, BAIRRO, CEP, MUNICIPIO, ESTADO, TELEFONE, CELULAR, EMAIL, CPF, DATANASCIMENTO) values('Natalia', 'rua centro', 'centro', '12345678','floripa', 'sc', '4899999999', '5548999999999', 'lais@email', '11111111111', '1999-10-24');
insert into FUNCIONARIO (NOME, ENDERECO, BAIRRO, CEP, MUNICIPIO, ESTADO, TELEFONE, CELULAR, EMAIL, CPF, DATANASCIMENTO, RG, CARGO, FUNCAO, DATAADMISSAO) values('NAT', 'rua centro', 'centro', '12345678','floripa', 'sc', '4899999999', '48999999999', 'lais@email', '11111111111', '1999-10-24', '1111111111', 'FISIO', 'PEELING', '2019-07-09');
INSERT INTO PROCEDIMENTO (NOME, SALA) VALUES('PEELING', '1A');
insert into CLIENTE (NOME, ENDERECO, BAIRRO, CEP, MUNICIPIO, ESTADO, TELEFONE, CELULAR, EMAIL, CPF, DATANASCIMENTO) values('Lais', 'rua centro', 'centro', '12345678','floripa', 'sc', '4899999998', '5548999407364', 'lais@email.com', '11111111118', '1999-10-24');

